name: "Cloud Foundry CLI GitHub Action"
description: "Run arbitrary commands using the CF CLI on GitHub Actions"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  API:
    description: "Target API Endpoint of Cloud Foundry"
    required: true
  USERNAME:
    description: "Username for API authentication"
    required: true
  PASSWORD:
    description: "Password for API authentication"
    required: true
  ORG:
    description: "Target Organization"
    required: false
  SPACE:
    description: "Target Space"
    required: false
  COMMAND:
    description: "Command to run using CF CLI"
    required: true
  VALIDATE:
    description: Whether or not to validate the CF API's TLS certificate
    required: false
    default: true
  DEBUG:
    description: Debug your deploy dir to list all folders
    required: false
    default: false  
  MANIFEST:
    description: The path to your CF application manifest
    required: true
    
runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.command }}
